name: open_in_colab
on:
  workflow_dispatch:
  pull_request:
defaults:
  run: { shell: bash }

jobs:

  build:
None
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu] }
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        python .github/scripts/open_in_colab.py
